### ISSUE TITLE
Deletion of CRD instance

### ISSUE THREAD

**Issue by johannwagner** [thcyron/skop#5]
Hey, 

I just tried to delete a CRD instance. Currently skop does not handle the deletion of CRD instances.

I have multiple ideas for this:

1. Create a shim around the k8s client library, which tracks the versions of the different resources and deletes them, if the CRD instance is deleted. Possible bugs, if you have to ensure cluster-wide resources.

2. Introduce cleanup function, which the user can use to delete the earlier created resources.

3. Provide a set of labels, that the user have to add to his/her resources, which are used to identify created resources by reconciler and delete them automagically.

I would prefer solution 3, but maybe you have other/better ideas. I would be fine with implementing this.

Feel free to contact me for a longer discussion on Twitter, iMessage, Telegram or mail, take a look at my profile.

Best Regards, 
   Johann

**Comment by thcyron** [comment]
I’m not sure I understand the problem correctly. If there is a CRD called `Foo` and it gets deleted, then all instances of `Foo` are also deleted by the garbage collector (see [`propagationPolicy`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#deleteoptions-v1-meta)).

**Comment by johannwagner** [comment]
I had to correct myself. I need to do a cleanup, if I delete a object with the type of my CRD. 

Example: I have a CRD, which is called Website. I create an instance of Website, which calls the reconcile function and leads to the creator of other resources, e.g. Deployments, Services, etc. 
If I delete the instance of Website, I want to remove all resources, but currently nothing happens I do not have a possibility to do anything and the resources get orphaned.

**Comment by thcyron** [comment]
You can accomplish exactly this by setting an owner reference:

https://github.com/thcyron/skop/blob/d8de80bf722f5b76f84449e0647b2cddcde518ce/example/main.go#L94-L102

**Comment by johannwagner** [comment]
Thanks a lot for your help, obviously I failed to read the docs.
